# Google App Engine configuration
runtime: python311

# Mumbai region
service: default

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables (you'll set these in Cloud Console)
env_variables:
  FLASK_ENV: production
  PYTHONPATH: /srv

# Resources
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
